banner = "Default Banner"
figlet_font = "chunky"
banner_color = "Magenta"
banner_position = "3"
shortcuts_color = "Cyan"
prompt_color = "Red"

[shortcuts]
nc.name = "ncdu"
nc.icon = " "
nc.command = "ncdu"

yt.name = "yt-dlp"
yt.icon = " "
yt.command = "yt-dlp"

rg.name = "ripgrep"
rg.icon = " "
rg.command = "rg"

e.name = "Emacs"
e.icon = " "
e.command = "emacs"
