banner = "Default Banner"
figlet_font = "poison"  # A more unusual font
banner_color = "Red"
shortcuts_color = "White"
prompt_color = "Blue"

[shortcuts]
py.name = "Python"
py.icon = " "
py.command = "python3"

jv.name = "Java"
jv.icon = " "
jv.command = "java"

ed.name = "Ed"       # The standard editor :)
ed.icon = ""      # No icon this time.
ed.command = "ed"

rust.name = "Rust"
rust.icon = " "
rust.command = "cargo"

web.name = "Browser"
web.icon = "爵 "
web.command = "firefox" # Or your preferred browser.
